[package]
name = "unrecoverable-errors-with-panic"
version = "0.1.0"
authors = ["JunSang Ryu <jsryu.dev@gmail.com>"]
edition = "2018"

[profile.release]
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

